// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.lbroudoux.roo.addon.taggable.domain;

import com.github.lbroudoux.roo.addon.taggable.domain.Tweet;
import java.util.List;
import java.util.Set;
import javax.persistence.ElementCollection;

privileged aspect Tweet_Roo_Taggable {
    
    @ElementCollection
    private Set<String> Tweet.tags = new java.util.HashSet<String>();
    
    public Set<String> Tweet.getTags() {
        return this.tags;
    }
    
    public void Tweet.addTag(String tag) {
        this.tags.add(tag);
    }
    
    public static List<Tweet> Tweet.findAllTweetsWithTag(String tag) {
        return entityManager().createQuery("SELECT o FROM Tweet o WHERE '" + tag + "' IN ELEMENTS(o.tags)", Tweet.class).getResultList();
    }
    
}
