// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.lbroudoux.roo.addon.taggable.domain;

import com.github.lbroudoux.roo.addon.taggable.domain.Tweet;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;

privileged aspect Tweet_Roo_Jpa_Entity {
    
    declare @type: Tweet: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Tweet.id;
    
    @Version
    @Column(name = "version")
    private Integer Tweet.version;
    
    public Long Tweet.getId() {
        return this.id;
    }
    
    public void Tweet.setId(Long id) {
        this.id = id;
    }
    
    public Integer Tweet.getVersion() {
        return this.version;
    }
    
    public void Tweet.setVersion(Integer version) {
        this.version = version;
    }
    
}
