// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.github.lbroudoux.roo.addon.taggable.domain;

import com.github.lbroudoux.roo.addon.taggable.domain.Tweet;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Tweet_Roo_Configurable {
    
    declare @type: Tweet: @Configurable;
    
}
